"""从 Registry 模型渲染各生成物字符串。"""
from __future__ import annotations

from .registry import Registry

HEADER = "# DO NOT EDIT — generated by `vortex cfg gen` from config/registry.yml"


def render_env(reg: Registry) -> str:
    c = reg.common
    lines = [
        HEADER,
        f"TZ={c.tz}",
        f"VORTEX_NETWORK={c.network}",
        f"VORTEX_IMAGE_BASE={c.image_base}",
        f"VORTEX_IMAGE_APP={c.image_app}",
        "",
    ]
    for s in reg.services:
        up = s.name.removeprefix("vortex_").upper()
        lines.append(f"VORTEX_{up}_PORT={s.port}")
        lines.append(f"VORTEX_{up}_BIND_ADDR={c.default_bind_addr}")
    return "\n".join(lines) + "\n"


def render_versions(reg: Registry) -> str:
    lines = [
        HEADER,
        "# pull-code.sh / build-release.sh 用 awk 解析本文件，字段固定 name/repo/ref/submodules。",
        "services:",
    ]
    for s in reg.services:
        lines.append(f"  - name: {s.name}")
        lines.append(f"    repo: {s.repo}")
        # 空 ref 投影为裸空（不带引号）：预留服务，构建/拉取时跳过。
        lines.append(f"    ref: {s.ref}" if s.ref else "    ref:")
        if s.submodules:
            lines.append("    submodules: true")
    return "\n".join(lines) + "\n"


def render_services_md(reg: Registry) -> str:
    lines = [
        "# 服务总表（生成）",
        "",
        HEADER,
        "",
        "| 服务 | 端口（内外一致） | 角色 | 健康检查 | 仓库 |",
        "|------|------|------|---------|------|",
    ]
    for s in reg.services:
        lines.append(f"| {s.name} | {s.port} | {s.role} | `{s.health}` | {s.repo} |")
    return "\n".join(lines) + "\n"


def render_architecture_md(reg: Registry) -> str:
    nodes = "\n".join(
        f'    {s.name.replace("vortex_", "")}["{s.name.replace("_", "-")} :{s.port}<br/>{s.role}"]'
        for s in reg.services
    )
    return (
        "# 系统拓扑（生成）\n\n"
        f"{HEADER}\n\n"
        "```mermaid\n"
        "graph TB\n"
        f'  subgraph host["宿主机 · {reg.common.network}"]\n'
        f"{nodes}\n"
        "  end\n"
        '  qmt -- QMTClient --> win["Windows · qmt-bridge :8000"]\n'
        "```\n"
    )
