"""从 Registry 模型渲染各生成物字符串。"""
from __future__ import annotations

from .registry import Registry

HEADER = "# DO NOT EDIT — generated by `vortex cfg gen` from config/registry.yml"


def render_env(reg: Registry) -> str:
    c = reg.common
    lines = [
        HEADER,
        f"TZ={c.tz}",
        f"VORTEX_NETWORK={c.network}",
        f"VORTEX_IMAGE_BASE={c.image_base}",
        f"VORTEX_IMAGE_APP={c.image_app}",
        "",
    ]
    for s in reg.services:
        up = s.name.removeprefix("vortex_").upper()
        lines.append(f"VORTEX_{up}_PORT={s.port}")
        lines.append(f"VORTEX_{up}_BIND_ADDR={c.default_bind_addr}")
    return "\n".join(lines) + "\n"
